### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by scottmessinger** [rubymood/jintastic#2]
I'm trying to deploy my app on heroku and I get this message:

App Failed to Start
usr/local/lib/ruby/1.8/fileutils.rb:1262:in `initialize': Read-only file system - /disk1/home/slugs/52039_24e5030_eb76/mnt/./app/views/jintastic/_in_place_editor.html.erb - Heroku has a read-only filesystem. See http://docs.heroku.com/constraints#read-only-filesystem (Errno::EROFS)

Do you have any idea if this problem can be fixed? Does this mean I can't use jintastic and heroku?

**Comment by scottmessinger** [comment]
In a github message on Feb. 17, rubymood wrote:

I have a solution but it's a hack: comment out the last line bottom of jintastic.rb in the jintastic library folder. This copy every asset each server start. So you need to manually copy these assets (jintastic/assets) into your project then push to heroku.

**Comment by rubymood** [comment]
Added jintastic asset generator. Jintastic now love heroku. Closed by fbafa43959e3657925a17cdb5e68729b7e643c9c
